module.exports = [
  // ── NSE India ──────────────────────────────────────────────────────────────
  { symbol: 'SUZLON.NS',      name: 'Suzlon Energy' },
  { symbol: 'ETERNAL.NS',     name: 'Eternal (Zomato)' },
  { symbol: 'BSE.NS',         name: 'BSE' },
  { symbol: 'HAL.NS',         name: 'HAL' },
  { symbol: 'DIXON.NS',       name: 'Dixon Technologies' },
  { symbol: 'IDFCFIRSTB.NS',  name: 'IDFC First Bank' },
  { symbol: 'JIOFIN.NS',      name: 'Jio Financial Services' },
  { symbol: 'CDSL.NS',        name: 'CDSL' },
  { symbol: 'MAZDOCK.NS',     name: 'Mazagon Dock' },
  { symbol: 'VBL.NS',         name: 'Varun Beverages' },
  { symbol: 'PVRINOX.NS',     name: 'PVR INOX' },
  { symbol: 'VISHALMEGA.NS',  name: 'Vishal Mega Mart' },
  { symbol: 'NBCC.NS',        name: 'NBCC' },
  { symbol: 'MOTHERSON.NS',   name: 'Samvardhana Motherson' },
  { symbol: 'IREDA.NS',       name: 'IREDA' },
  { symbol: 'SWIGGY.NS',      name: 'Swiggy' },
  { symbol: 'PGEL.NS',        name: 'PG Electroplast' },
  { symbol: 'TATAPOWER.NS',   name: 'Tata Power' },
  { symbol: 'GRSE.NS',        name: 'Garden Reach' },
  { symbol: 'BAJFINANCE.NS',  name: 'Bajaj Finance' },
  { symbol: 'KALYANKJIL.NS',  name: 'Kalyan Jewellers' },
  { symbol: 'YESBANK.NS',     name: 'Yes Bank' },
  { symbol: 'M&M.NS',         name: 'Mahindra & Mahindra' },
  { symbol: 'INDIGO.NS',      name: 'IndiGo' },
  { symbol: 'AAVAS.NS',       name: 'Aavas Financiers' },

  // ── US Markets ─────────────────────────────────────────────────────────────
  { symbol: 'MSFT',   name: 'Microsoft' },
  { symbol: 'META',   name: 'Meta' },
  { symbol: 'AMZN',   name: 'Amazon' },
  { symbol: 'NVDA',   name: 'Nvidia' },
  { symbol: 'TSLA',   name: 'Tesla' },
  { symbol: 'AMD',    name: 'AMD' },
  { symbol: 'NOW',    name: 'ServiceNow' },
  { symbol: 'NFLX',   name: 'Netflix' },
  { symbol: 'RKLB',   name: 'Rocket Lab' },
  { symbol: 'GOOGL',  name: 'Alphabet' },
];
